version: '3.8'

services:
  spark-master:
    container_name: spark-master
    image: bitnami/spark:latest
    ports:
      - "8081:8080"
      - "7077:7077"
    volumes:
      - ./docker_data/spark-master:/bitnami/spark
    environment:
      - SPARK_MODE=master

  spark-worker:
    container_name: spark-worker
    image: bitnami/spark:latest
    ports:
      - "8082:8081" # Optionally expose different ports for each worker if needed
      # - "36629:36629"
    volumes:
      - ./docker_data/spark-worker:/bitnami/spark
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
    # depends_on:
    #   - spark-master